# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: k0s
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: k0s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - test.foo.com
    secretName: secret-tls
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-web
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: external-web
spec:
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: external-web
  namespace: k0s
subsets:
  - addresses:
      - ip: 192.168.1.100  # VM 上的 Web 服務 IP
    ports:
      - port: 8080