replicaCount: 3
image:
  tag: stable
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi
hostname: web.example.com
certSecret: wildcard-tls
certificate:
  dnsNames:
    - example.com
    - '*.example.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod